### PR TITLE
Added the Debian os Part for Web2 ui. 

### PR DESCRIPTION
**Pull request by tduemesnil**
Mainly a copy of the RedHat version which uses APT as Package Manager.
Added a Modified Path for the SQL Schema files.
Different Package for Debian

HTH
Thomas

### CODE REVIEW

**Comment by valentinogagliardi** [comment]
Hello.
Would you check out the conflicts and modify the PR accordingly?
Thank you!

**Comment by tduemesnil** [comment]
Hello. 
I fixed the conflict in defaults and modified the var name to you new naming schema.

HTH

**Comment by valentinogagliardi** [comment]
Thank you, I'm going to test that and I'll merge the PR when done.

**Comment by valentinogagliardi** [comment]
I saw you placed `login_user=root` and `login_pass={{ mysql_root_db_pass }}` in `icinga2-ansible-web2-ui/tasks/icinga2_web2_ui_Debian_install.yml`. I think it'd better to omit that and let `.my.cnf` do the job as in the RH tasks. Starting on a fresh server, one could install MariaDB/Mysql, then install Icinga2 with UI and at the end runs `mysql_secure_installation` setting up the Mysql root password. Would you mind to remove login_user and login_pass? Apart from this the tasks works fine.
Thank you very much.

**Comment by tduemesnil** [comment]
The mysql role (bennojoy.mysql) I use to setup the server immediately sets a root password. And creates a ~/.my.cnf file for the root user. Are the credentials use during the script ?

**Comment by valentinogagliardi** [comment]
When the `.my.cnf` is already in place, there is no need to pass the credential to the tasks, Ansible automatically use `.my.cnf`

**Comment by tduemesnil** [comment]
Always something to learn.

**Pull request merged**
